FROM ubuntu:24.04

RUN yes | unminimize

RUN apt update && apt install -y \
    build-essential \
    curl \
    file \
    gdb \
    git \
    man \
    valgrind \
    wget \
    libglfw3 \
    libglfw3-dev \
    libglu1-mesa-dev \ 
    libglm-dev \
    freeglut3-dev \
    mesa-common-dev \
    libglew-dev \ 
    libxxf86vm-dev \
    libxi-dev